image: node:18

stages:
  - build
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:
  stage: build
  script:
    - npm ci
    - npm run docs:build
  artifacts:
    paths:
      - .vitepress/dist

pages:
  stage: deploy
  script:
    - mv .vitepress/dist public
  artifacts:
    paths:
      - public
  only:
    - main
